packages:
  - packages/**/*
  - service/**/*

catalog:
  '@cloudflare/workers-types': ^4.20260317.1
  '@types/node': ^25.5.0
  dayjs: ^1.11.19
  next: 16.2.3
  react: ^19.2.4
  react-dom: ^19.2.4
  tsup: ^8.5.0
  typescript: ^6.0.0
  wrangler: ^4.76.0
  zod: ^4.0.0

sharedWorkspaceLockfile: true
