packages:
  - packages/**/*
  - service/**/*

catalog:
  '@cloudflare/workers-types': ^4.20260111.0
  '@types/node': ^22.19.5
  dayjs: ^1.11.19
  next: 15.4.10
  react: ^19.2.3
  react-dom: ^19.2.3
  tsup: ^8.5.0
  typescript: ^5.9.3
  wrangler: ^4.58.0
  zod: ^3.25.76

sharedWorkspaceLockfile: false
