// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/discord": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/:guildId": {
    params: {
      "guildId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/discord" | "/auth/callback" | "/auth/logout" | "/dashboard" | "/dashboard/:guildId";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.discord.tsx": {
    id: "routes/auth.discord";
    page: "/auth/discord";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/:guildId";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.$guildId.tsx": {
    id: "routes/dashboard.$guildId";
    page: "/dashboard/:guildId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.discord": typeof import("./app/routes/auth.discord.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.$guildId": typeof import("./app/routes/dashboard.$guildId.tsx");
};