name: PR Check
on:
  pull_request:
    paths:
      - 'service/vspo-schedule/v2/web/**'
      - 'packages/**'
      - '.github/workflows/pr-check.yaml'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'service/vspo-schedule/v2/web/**'

  biome-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Biome Check
        run: pnpm biome:check

  typescript-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: TypeScript Check
        run: pnpm tsc

  knip-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Knip Check
        run: pnpm knip

  textlint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Textlint Check
        run: pnpm textlint
