name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm
        
      - name: Run CI with Turbo
        run: pnpm run ci
        env:
          TURBO_TELEMETRY_DISABLED: 1
          SKIP_WRANGLER_CONFIG_CHECK: yes
